# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Run tests
on:
  push:
    branch: [main]

jobs:
  verify-contracts:
    name: Verify against api - ${{ github.ref_name }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.45
      - run: bun install
      - run: bun run test:contract

      - name: Publish pacts to broker
        if: ${{ vars.PACT_BROKER_URL != '' }}
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/tests/contract/pacts:/pacts \
            pactfoundation/pact-cli:latest \
            publish /pacts \
            --consumer-app-version ${{ github.sha }} \
            --branch ${{ github.ref_name }} \
            --broker-base-url ${{ vars.PACT_BROKER_URL }} \
            --broker-username ${{ vars.PACT_BROKER_USERNAME }} \
            --broker-password ${{ secrets.PACT_BROKER_PASSWORD }}

      - name: Can I deploy?
        if: ${{ vars.PACT_BROKER_URL != '' }}
        run: |
          docker run --rm pactfoundation/pact-cli:latest \
            broker can-i-deploy \
            --pacticipant paperwall-lib \
            --version ${{ github.sha }} \
            --retry-while-unknown 12 \
            --retry-interval 30 \
            --to-environment production \
            --broker-base-url ${{ vars.PACT_BROKER_URL }} \
            --broker-username ${{ vars.PACT_BROKER_USERNAME }} \
            --broker-password ${{ secrets.PACT_BROKER_PASSWORD }}
